const path = {
    PUBLIC: '',
    HOME: '/',
    ADMIN_ADD_PRODUCTS: '/add-products',
    ADMIN_EDIT_PRODUCTS: '/admin/edit-products',
    MENS: '/mens',
    WOMENS: '/womens',
    TOPS: '/tops',
    BOTTOMS: '/bottoms',
    OUTERWEARS: '/outerwears',
    ACCESSORIES: '/accessories',
    PRODUCTDETAIL: '/:catelory/:id',
    LOGIN: '/login',
    SIGNUP: '/signup',
    ALL_USERS: '/listusers',
    CART: '/cart',
    ORDER_HISTORY: '/order-history',
    ALL_ORDER: '/all-order',
}
export default path;